import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import Projects from './projects'
import { Footer } from '../components/Footer'
import Technologies from './technologies'
import { Header } from '../components/Header'
import About from './about'
import Lottie from 'react-lottie'

import ScrollAnimation from 'react-animate-on-scroll';

import animationData from '../lotties/downAnimation.json'
import { useEffect, useState } from 'react'
import { Link } from 'react-scroll'

const Home: NextPage = () => {

  const [scrollPosition, setScrollPosition] = useState(0);
    const handleScroll = () => {
        const position = window.pageYOffset;
        setScrollPosition(position);
    };
    useEffect(() => {
        window.addEventListener('scroll', handleScroll, { passive: true });
    
        return () => {
            window.removeEventListener('scroll', handleScroll);
        };
    }, []);

  // Lottie
  const defaultOptions = {
    loop: true,
    autoplay: true,
    animationData: animationData,
    rendererSettings: {
      preserveAspectRatio: "xMidYMid slice"
    }
  };

  return (<>
      <Head>
        <title>Dev Oliveira</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1"></meta>
        <meta name="description" content="Generated by create next app" />
        <meta charSet="UTF-8"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>
  <div className={styles.container}><div className={styles.home}>
    <Header/>
    <div className={styles.content}>       
      <main className={styles.main}>
        <ScrollAnimation 
          delay={1000}
          animateIn="animate__fadeIn"
          initiallyVisible={true}
          animateOnce={true}
        >
          <h1 className={styles.title}>
            Hi, I am Weslley a problem solver.
          </h1>
        </ScrollAnimation>
        <ScrollAnimation
          delay={1300} 
          animateIn="animate__fadeIn"
          initiallyVisible={true}
          animateOnce={true}
        >
          <p>
            Front-end Web Developer, technology and programming.
          </p>
        </ScrollAnimation>
        
        <ScrollAnimation 
            delay={1000}
            animateIn="animate__fadeIn"
            animateOnce={true}            
          >
        <div className={styles.action}>
          
            
            <button className="first">Download CV</button>
          
            <button>Contact Me</button>
          
        </div>    
        </ScrollAnimation>    
      </main>
      <section className={styles.section}>
      <ScrollAnimation 
            delay={200}
            animateIn="animate__flipInX"      
          >
      
        <img src="/profile.jpg" alt="Weslley Oliveira"/>

        </ScrollAnimation>
      </section>             
    </div>
    
    <Link activeClass="active" to="about" spy={true} smooth={true} offset={0} duration={1000} >
      <div className={`${styles.animation} ${scrollPosition >= 100 && styles.hide}`}>
        <Lottie 
            options={defaultOptions}
            height={60}
            width={60}
          />
      </div>
    </Link>


  </div>
  <div className={styles.shapeDivider}>
      <svg data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 120" preserveAspectRatio="none">
          <path d="M0,0V46.29c47.79,22.2,103.59,32.17,158,28,70.36-5.37,136.33-33.31,206.8-37.5C438.64,32.43,512.34,53.67,583,72.05c69.27,18,138.3,24.88,209.4,13.08,36.15-6,69.85-17.84,104.45-29.34C989.49,25,1113-14.29,1200,52.47V0Z" opacity=".25" className={styles.shapeFill}></path>
          <path d="M0,0V15.81C13,36.92,27.64,56.86,47.69,72.05,99.41,111.27,165,111,224.58,91.58c31.15-10.15,60.09-26.07,89.67-39.8,40.92-19,84.73-46,130.83-49.67,36.26-2.85,70.9,9.42,98.6,31.56,31.77,25.39,62.32,62,103.63,73,40.44,10.79,81.35-6.69,119.13-24.28s75.16-39,116.92-43.05c59.73-5.85,113.28,22.88,168.9,38.84,30.2,8.66,59,6.17,87.09-7.5,22.43-10.89,48-26.93,60.65-49.24V0Z" opacity=".5" className={styles.shapeFill}></path>
          <path d="M0,0V5.63C149.93,59,314.09,71.32,475.83,42.57c43-7.64,84.23-20.12,127.61-26.46,59-8.63,112.48,12.24,165.56,35.4C827.93,77.22,886,95.24,951.2,90c86.53-7,172.46-45.71,248.8-84.81V0Z" className={styles.shapeFill}></path>
      </svg>
  </div>  
  
  
    
    </div>
    <About/>
    <Projects/>
    <Technologies/>
    <Footer/>
    
    </>)
}

export default Home
